### ISSUE TITLE
Broken images in wrong fields

### ISSUE THREAD

**Issue by Vaanen** [upday7/WebQuery#2]
Hello, so the addon is a great idea, unfortunately it doesn't work at all on my anki. When i do a capture, i see the image saved as a small "?" sign in a blue box and it's always in the wrong field. For example, if i choose the field "Image" as destination, it puts it in the Grammar field while removing everything that was previously there. I then tried to save it to an empty grammar field, and it did the same thing, but on the meaning field, making me lose the actual meaning of the card while having no image

**Comment by upday7** [comment]
This is because the key order issue .. I’ll fix this in recently

**Comment by upday7** [comment]
Fix bug in Anki2.0 for captured images being saved in incorrect field. Please update the addon.

**Comment by upday7** [comment]
@Vaanen Broken image has been fixed just now as i encountered as well .. this is because the encoding error of unicodes in python2. Please just have an update.
