### ISSUE TITLE
not displaying browser properly 

### ISSUE THREAD

**Issue by Alexnder77** [upday7/WebQuery#21]
![skarmbild 226](https://user-images.githubusercontent.com/24762643/52899784-37d20900-31ee-11e9-83ee-47ed15a25754.png)

**Comment by Alexnder77** [comment]
the options and capture image fields makes up about 90% of the window while the browser is barely shown..

**Comment by sissiwonder** [comment]
same problem

**Comment by sissiwonder** [comment]
> the options and capture image fields makes up about 90% of the window while the browser is barely shown..

Did you fix it?

**Comment by sissiwonder** [comment]
> the options and capture image fields makes up about 90% of the window while the browser is barely shown..

![image](https://user-images.githubusercontent.com/41968535/53287004-73cd1700-3776-11e9-89ff-427976c3f78f.png)

I've updated the new version and the problem was fixed. I don't know why the author didn't update it in anki...
