### ISSUE TITLE
When using C to make selection on mac osx high sierra it 'crops' the view.

### ISSUE THREAD

**Issue by jandoor** [upday7/WebQuery#3]
Here are the images before and after selecting the C function.
Before
<img width="1280" alt="1" src="https://user-images.githubusercontent.com/35034436/34493184-1065421a-efeb-11e7-8171-72bcb4e7743c.png">
After
<img width="1280" alt="2" src="https://user-images.githubusercontent.com/35034436/34493182-104abcce-efeb-11e7-9171-647d21aa9496.png">

**Comment by upday7** [comment]
@jandoor Hello, I have fixed the dock width by default in anki2.0 and this is a bug of PyQt. Please try:
https://github.com/upday7/WebQuery/tree/fix%233docksize/2.0
