### ISSUE TITLE
Ability to choose which field to perform query with

### ISSUE THREAD

**Issue by glutanimate** [upday7/WebQuery#5]
First of all: Fantastic job on the add-on! I could see this coming in handy for a variety of use cases and with all kinds of subjects.

One addition which I think the add-on could really benefit from, is a config option to set which field to look up. In most cases looking at the first field should be sufficient, but with some note types that might not be helpful. Take the Note ID add-on for instance: It uses a note type where the first field is always set to the NID. Needless to say, querying the web for the NID is not going to yield any relevant results.

If you could define which field to use, ideally on a per-note-type basis, that would really help.

Either way, thanks again for all the work you've put into this add-on! Very much looking forward to using this more extensively in the future.

**Comment by upday7** [comment]
@glutanimate Hello big G : ) thank you for your complements, and im very happy to hear from you.  I have pushed this enhancement to "2.0" folder, please try it out, hopping that there's no issues. and i founded another problem of resizing dock widget in anki .. so additionally added a button of resizing aside the options.

[https://github.com/upday7/WebQuery/tree/master/2.0](https://github.com/upday7/WebQuery/tree/master/2.0)

**Comment by glutanimate** [comment]
Awesome, thanks for working this in so quickly! Just gave the latest build a try with a few of my note types and the field mapping seems to be working perfectly. Resizing also seems to work well with the new button on Anki 2.0. Kudos! :)

**Comment by upday7** [comment]
Looking foward to any new ideas from you. : D
