### ISSUE TITLE
Issue Report Multiple Web Query on the menu list.

### ISSUE THREAD

**Issue by lizvoila** [upday7/WebQuery#7]
1. Multiple Web Query..
![2018-01-22 16 29 25](https://user-images.githubusercontent.com/23472458/35211613-2ec1fc88-ff92-11e7-8f48-25be0495a700.png)
![2018-01-22 16 36 14](https://user-images.githubusercontent.com/23472458/35211672-70647a94-ff92-11e7-8538-c1250d7f766e.png)

2. When Web Query is on, the answer tabs do not show up properly, it takes a few cards before the proper tabs are back. As the same picture shows, the answer tabs are lagging/disappearing..
![2018-01-22 16 36 14](https://user-images.githubusercontent.com/23472458/35211672-70647a94-ff92-11e7-8538-c1250d7f766e.png)

Info on Device:
Mac, Anki 2.0.40, Newest add-on version.

**Comment by upday7** [comment]
fixed in version 1.2.42
